### ISSUE TITLE
Controller Pinout

### ISSUE THREAD

**Issue by ianwitherow** [mauntrelio/XFEL_desk#1]
Hey! Thanks for sharing this project. Just got some sit-stands at work that use the exact same controller.
I found your images showing which pins are common/up/down, but could you point me to which pins are for reading the current state? I glanced at the code and I believe I'm looking for what you reference as echo and trigger.

Thanks!

**Comment by mauntrelio** [comment]
Hi!
I defintely should update documentation for this project.
The first time I uploaded the code to Github, I did not have distance sensor at all. I think this is what you are referring to about current state...
Well, this is done via an additional component (Ultrasonic Sensor HC-SR04) attached under the table and connected to pins 9 and 10 of the Arduino Nano, not via the motor controller (which probably has some way to give such status but I have no clue)
![IMG_20180610_104609](https://user-images.githubusercontent.com/1818574/83263377-c89fde80-a1be-11ea-8145-993e963d68dc.jpg)
